# Generated by Django 6.0 on 2025-12-21 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Menu item label (e.g., 'Home', 'Reels bundle ₹99')", max_length=100)),
                ('url', models.CharField(help_text="URL or link (e.g., '/', '/?price=99', '#reels-bundle')", max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this menu item')),
                ('menu_type', models.CharField(choices=[('link', 'Regular Link'), ('dropdown', 'Dropdown Menu')], default='link', help_text='Regular link or dropdown menu', max_length=20)),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Open link in new tab')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Navigation Menu Item',
                'verbose_name_plural': 'Navigation Menu Items',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='NavigationMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Submenu item label (e.g., 'Instagram', 'WhatsApp')", max_length=100)),
                ('url', models.CharField(help_text='URL or link', max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Display order within dropdown')),
                ('is_active', models.BooleanField(default=True)),
                ('open_in_new_tab', models.BooleanField(default=True, help_text='Open link in new tab')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_menu', models.ForeignKey(limit_choices_to={'menu_type': 'dropdown'}, on_delete=django.db.models.deletion.CASCADE, related_name='dropdown_items', to='api.navigationmenu')),
            ],
            options={
                'verbose_name': 'Navigation Menu Dropdown Item',
                'verbose_name_plural': 'Navigation Menu Dropdown Items',
                'ordering': ['order', 'label'],
            },
        ),
    ]
