# Generated by Django 6.0 on 2025-12-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_navigationmenu_navigationmenuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationmenuitem',
            name='parent_menu',
        ),
        migrations.DeleteModel(
            name='NavigationMenu',
        ),
        migrations.DeleteModel(
            name='NavigationMenuItem',
        ),
    ]
