# Generated by Django 6.0 on 2025-12-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_navigationmenuitem_parent_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, help_text='Proof of payment uploaded by customer', null=True, upload_to='payment_screenshots/'),
        ),
        migrations.AddField(
            model_name='product',
            name='payment_qr',
            field=models.ImageField(blank=True, help_text='QR code image to display on payment page', null=True, upload_to='payment_qr/'),
        ),
    ]
