# Generated by Django 6.0 on 2025-12-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_payment_screenshot_product_payment_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='payment_qr_default',
            field=models.ImageField(blank=True, help_text='Default QR shown on payment page when product QR is not set', null=True, upload_to='payment_qr/'),
        ),
    ]
