# Generated by Django 6.0 on 2025-12-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sitesettings_payment_qr_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy',
            field=models.TextField(blank=True, default='', help_text='Privacy Policy content'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='refund_policy',
            field=models.TextField(blank=True, default='', help_text='Refund Policy content'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_and_conditions',
            field=models.TextField(blank=True, default='', help_text='Terms & Conditions content'),
        ),
    ]
