# Generated by Django 6.0 on 2025-12-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='from_email',
            field=models.EmailField(blank=True, default='', help_text='Override sender email for outgoing messages (leave blank to use DEFAULT_FROM_EMAIL)', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_email',
            field=models.EmailField(default='support@skilcart.com', help_text='Support contact email shown to customers', max_length=254),
        ),
    ]
